// libs/al-react/.storybook/with-preset.tsx
// The @southleft/al-react preset decorator. Spec: 2026-07-28-react-storybook-preset-switcher.
//
// The React counterpart of `@southleft/al-web-components/.storybook/with-preset.ts`. Both
// read the SAME `presets.ts` (imported below by relative path — @southleft/al-react
// already reaches sideways into @southleft/al-web-components that way for `main.css` and
// the icon font), so preset ids, labels and axis tuples cannot drift between
// the two Storybooks.
//
// Why the two decorators are not line-for-line identical:
//
//   * lit-html's `brand=${…}` writes an ATTRIBUTE. `@lit/react`'s
//     `createComponent` writes a PROPERTY for every key that is `in
//     elementClass.prototype` (`create-component.js` -> `setProperty`), and
//     `<al-theme>`'s five axes are `@property accessor`s with no `reflect`, so
//     a React prop alone never produces the attribute that
//     `:host([brand='southleft'])` selects on. `ALTheme` (the wrapper) closes
//     that gap — see `src/components/Theme/Theme.tsx`.
//
//   * @southleft/al-react registers with `suffix: PackageJson.version`, so the tag here is
//     `al-theme-1-0-0`, not `al-theme`. Nothing in this path calls
//     `closest('al-theme')` (R6): the axes are set on the element this
//     decorator renders, so the hardcoded tag name in
//     `theme-switcher.ts:109` is never consulted.
//
// There is no stylesheet swap and no `document.head` mutation on either side —
// `2026-07-28-scoped-token-emission-brand-wiring` moved `brand` into
// `<al-theme>`'s own compiled `:host([brand])` styles, which travel with
// `dist/components/theme/theme.js` and therefore with the wrapper.

import React from 'react';
import type { Decorator } from '@storybook/react-vite';
import { ALTheme } from '../src/components/Theme';
import { getPreset, type Preset } from '../../al-web-components/.storybook/presets';

/** `parameters.alPreset = { disable: true }` opts a story out entirely. */
function isDisabled(context: { parameters?: { alPreset?: { disable?: boolean } } }): boolean {
  return context.parameters?.alPreset?.disable === true;
}

/**
 * Repaint the preview iframe's own surface to match the active preset —
 * ported from `@southleft/al-web-components/.storybook/with-preset.ts` (see that file
 * for why neither a painted wrapper `<div>` nor a `:root` stylesheet swap is
 * acceptable). `<al-theme>` is `display: contents`, so it paints nothing; the
 * iframe background comes from the altitude-DARK `:root` bundle and does not
 * move when the one-click toggle flips to light.
 *
 * One deliberate difference: the selector is `[data-al-preset]` alone, not
 * `al-theme[data-al-preset]` — @southleft/al-react registers with a version suffix, so
 * the element here is `al-theme-1-0-0` and a tag-qualified selector would
 * never match.
 */
const SURFACE_TOKENS = [
  '--al-theme-color-background-default-weak',
  '--al-theme-color-content-default',
] as const;

function syncPreviewSurface(): void {
  requestAnimationFrame(() => {
    const el = document.querySelector('[data-al-preset]');
    if (!el) return;
    const cs = getComputedStyle(el);
    for (const token of SURFACE_TOKENS) {
      const value = cs.getPropertyValue(token).trim();
      if (value) document.documentElement.style.setProperty(token, value);
    }
  });
}

export const withPreset: Decorator = (Story, context) => {
  // Opt-out, mirroring the web-components side. `<al-theme-switcher>` walks up
  // for a theme host and takes the scoped path when it finds one, so inside a
  // wrapper its own stories demonstrate only half of what they document.
  if (isDisabled(context)) return <Story />;

  const preset: Preset = getPreset(context.globals?.alPreset);
  syncPreviewSurface();

  // `density` / `contrast` / `shape` / `motion` stay OPTIONAL in the preset
  // tuple and are written only when a preset names them — copied verbatim
  // from the web-components decorator. `contrast="normal"` / `shape="default"`
  // / `motion="full"` match no rule, and an absent attribute is the honest
  // expression of "this preset takes no position on this axis".
  return (
    <ALTheme
      brand={preset.brand}
      mode={preset.mode}
      density={preset.density}
      contrast={preset.contrast}
      shape={preset.shape}
      motion={preset.motion}
      data-al-preset={preset.id}
    >
      <Story />
    </ALTheme>
  );
};

// libs/al-web-components/.storybook/with-preset.ts
// The preset decorator. Specs: 2026-07-28-storybook-preset-toolbar-switcher,
// then 2026-07-28-scoped-token-emission-brand-wiring.
//
// This used to be a TWO-mechanism decorator: `brand` could only be delivered
// by swapping a whole `:root` stylesheet into `<head>`, because every bundle is
// emitted unlayered and `components/theme/theme.scss` had no `:host([brand])`
// rule. All four axes now travel as attributes on one `<al-theme>` element —
// the emitter writes `:host([brand])` / `:host([brand][mode])` blocks into the
// component's own styles (`styles/dist-v5/scss/host/`). The stylesheet swap,
// its always-last ordering guard and the `style#al-preset-tokens` element are
// gone.
//
// Consequences worth knowing:
//   * there is no global state left, so two stories on one docs page could
//     legitimately carry different presets;
//   * a preset now applies inside the wrapper only — nothing leaks to
//     `document.head`, so the Storybook chrome and any un-wrapped story are
//     untouched by construction rather than by careful id management.

import { html } from 'lit';
import { ifDefined } from 'lit/directives/if-defined.js';
import type { Decorator } from '@storybook/web-components';
import { ALTheme } from '../components/theme/theme';
import { getPreset, type Preset } from './presets';

// R5 / spec risk R-1, belt-and-braces half two. `.storybook/auto-registry.ts`
// is imported first from `preview.ts` so `alAutoRegistry` is already true by
// the time `../components/theme/theme` is evaluated above — but if someone
// reorders those imports, `theme.ts:58-60` silently declines to register and
// every axis dies without an error. Define it here unconditionally so the
// decorator cannot render an un-upgraded wrapper.
if (customElements.get(ALTheme.el) === undefined) {
  customElements.define(ALTheme.el, ALTheme);
}

/** `parameters.alPreset = { disable: true }` opts a story out entirely. */
function isDisabled(context: { parameters?: { alPreset?: { disable?: boolean } } }): boolean {
  return context.parameters?.alPreset?.disable === true;
}

/**
 * Repaint the preview iframe's own surface to match the active preset.
 *
 * `<al-theme>` is `display: contents`, so it resolves tokens but paints
 * NOTHING. The iframe's background comes from `main.scss`'s `:root` bundle,
 * which is altitude-DARK and does not move when the preset does — so switching
 * to light left every story sitting on a black page. That was always true; the
 * light/dark toggle in `manager.js` just made it impossible to miss.
 *
 * Deliberately NOT fixed by wrapping the story in a painted `<div>`: that would
 * put an extra box between the canvas and every story, which `layout:
 * 'fullscreen'` and grid/flex stories can feel. Deliberately NOT fixed by
 * swapping a `:root` stylesheet either — that is the global mechanism spec
 * `2026-07-28-scoped-token-emission-brand-wiring` removed.
 *
 * Instead: read the two surface tokens the theme element already computes and
 * copy them onto `body`. No hardcoded colours, no added DOM, and it is a
 * Storybook-only affordance — nothing here ships in the library.
 */
const SURFACE_TOKENS = [
  // `styles/core/base.scss` paints `body` with `--al-theme-color-body-background`,
  // and `styles/main.scss` paints Storybook's own `.docs-story` canvas with it
  // too. That token is an ALIAS for `--al-theme-color-background-default-weak`
  // (see the emitted bundles), and the alias itself is mode-invariant — so
  // repointing the weak token is enough to move both surfaces.
  '--al-theme-color-background-default-weak',
  '--al-theme-color-content-default',
] as const;

function syncPreviewSurface(): void {
  requestAnimationFrame(() => {
    const el = document.querySelector('al-theme[data-al-preset]');
    if (!el) return;
    const cs = getComputedStyle(el);
    for (const token of SURFACE_TOKENS) {
      const value = cs.getPropertyValue(token).trim();
      if (value) document.documentElement.style.setProperty(token, value);
    }
  });
}

export const withPreset: Decorator = (story, context) => {
  // Opt-out. Used by the `<al-theme-switcher>` stories: that component walks up
  // for an `<al-theme>` ancestor (`theme-switcher.ts:109-113`) and takes the
  // scoped path when it finds one, so inside a wrapper its own global-swap
  // fallback is unreachable and only `mode` and `brand` attributes move.
  if (isDisabled(context)) return story();

  const preset: Preset = getPreset(context.globals?.alPreset);
  syncPreviewSurface();

  // `density` / `contrast` / `shape` / `motion` are still written only when
  // the preset names them — not because `comfortable` is dangerous any more
  // (that rule is gone), but because e.g. `contrast="normal"` / `shape="default"`
  // / `motion="full"` match no rule and an absent attribute is the honest
  // expression of "this preset does not take a position".
  return html`<al-theme
    brand=${preset.brand}
    mode=${preset.mode}
    density=${ifDefined(preset.density)}
    contrast=${ifDefined(preset.contrast)}
    shape=${ifDefined(preset.shape)}
    motion=${ifDefined(preset.motion)}
    data-al-preset=${preset.id}
    >${story()}</al-theme
  >`;
};
