// apps/angular/src/app/dashboard/dashboard.component.ts
import { Component } from '@angular/core';

import "@southleft/al-web-components/dist/components/calendar/calendar.js";

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss'
})
export class DashboardComponent {}

<div class="al-u-grid al-u-gap--lg" style="height: 100%;">
  <div class="al-u-grid__item col:7@md">
    <app-fpo>
      Coming soon
    </app-fpo>
  </div>
  <al-calendar class="al-u-grid__item col:5@md row:2@md"></al-calendar>
  <div class="al-u-grid__item col:7@md">
    <app-fpo>
      Coming soon
    </app-fpo>
  </div>
  <div class="al-u-grid__item col:12@md">
    <app-fpo>
      Coming soon
    </app-fpo>
  </div>
</div>

// apps/svelte/src/lib/Dashboard.svelte
<script lang="ts">
  import Fpo from './Fpo.svelte'
  import '@southleft/al-web-components/dist/components/calendar/calendar';
</script>

<div class="al-u-grid al-u-gap--lg" style="height: 100%;">
  <div class="al-u-grid__item col:7@md">
    <Fpo></Fpo>
  </div>
  <al-calendar class="al-u-grid__item col:5@md row:2@md"></al-calendar>
  <div class="al-u-grid__item col:7@md">
    <Fpo></Fpo>
  </div>
  <div class="al-u-grid__item col:12@md">
    <Fpo></Fpo>
  </div>
</div>
