// apps/react/src/routes/Dashboard.js
import { ALCalendar } from 'al-react/dist/src';
import FPo from '../components/Fpo';

const Home = () => {
  return (
    <div className="al-u-grid al-u-gap--lg" style={{height: "100%"}}>
        <div className="al-u-grid__item col:7@md">
          <FPo>
            Coming soon
          </FPo>
        </div>
        <ALCalendar className="al-u-grid__item col:5@md row:2@md"></ALCalendar>
        <div className="al-u-grid__item col:7@md">
          <FPo>
            Coming soon
          </FPo>
        </div>
        <div className="al-u-grid__item col:12@md">
          <FPo>
            Coming soon
          </FPo>
        </div>
      </div>
  );
};

export default Home;

// apps/svelte/src/lib/Dashboard.svelte
<script lang="ts">
  import Fpo from './Fpo.svelte'
  import 'al-web-components/dist/components/calendar/calendar';
</script>

<div class="al-u-grid al-u-gap--lg" style="height: 100%;">
  <div class="al-u-grid__item col:7@md">
    <Fpo></Fpo>
  </div>
  <al-calendar class="al-u-grid__item col:5@md row:2@md"></al-calendar>
  <div class="al-u-grid__item col:7@md">
    <Fpo></Fpo>
  </div>
  <div class="al-u-grid__item col:12@md">
    <Fpo></Fpo>
  </div>
</div>
