// apps/react/src/App.jsx
import { Routes, Route } from 'react-router-dom';
import Dashboard from './components/Dashboard';
import Layout from './components/Layout';
import JobBoard from './components/JobBoard';
import './App.scss';

const App = () => {
  return (
    <Routes>
      <Route path="/" element={<Layout />}>
        <Route path="/dashboard" element={<Dashboard />} />
        <Route index element={<JobBoard />} />
        <Route path="*" element={<JobBoard />} />
      </Route>
    </Routes>
  );
};

export default App;

// apps/svelte/src/App.svelte
<script lang="ts">
  // @ts-nocheck
  import { Router, Route } from 'svelte-routing'
  import Layout from './lib/Layout.svelte'
  import Dashboard from './lib/Dashboard.svelte'
  import JobBoard from './lib/JobBoard.svelte'
</script>

<Router>
  <Layout>
    <Route path="/"><JobBoard /></Route>
    <Route path="/dashboard"><Dashboard /></Route>
    <Route path="*"><JobBoard /></Route>
  </Layout>
</Router>
